Repository StatCan/aaw-kubeflow-containers, pull requests merged in 2022-08, with the labels that each got.

#379 chore(allowedlist): include CVE-2022-34749 to whitelist
  .github/containerscan/allowedlist.yaml
Labels: area/security, auto-deploy

#378 chore(qgis_gpg_key): update gpg key to 2022
  docker-bits/6_remote-desktop.Dockerfile
  output/remote-desktop/Dockerfile
  output/remote-desktop/qgis-2021.gpg.key
  output/remote-desktop/qgis-2022.gpg.key
  output/remote-desktop/remote-desktop/qgis.sh
  resources/remote-desktop/qgis-2021.gpg.key
  resources/remote-desktop/qgis-2022.gpg.key
  scripts/remote-desktop/qgis.sh
Labels: auto-deploy

#373 Add missing profile
  .github/workflows/build_push.yaml
  output/docker-stacks-datascience-notebook/start-custom.sh
  output/jupyterlab-cpu/start-custom.sh
  output/jupyterlab-pytorch/start-custom.sh
  output/jupyterlab-tensorflow/start-custom.sh
  output/remote-desktop/start-custom.sh
  output/rstudio/start-custom.sh
  output/sas/start-custom.sh
  resources/common/start-custom.sh
Labels: auto-deploy

#386 fix(trino): add default JNA storage location
  output/docker-stacks-datascience-notebook/shell_helpers.sh
  output/jupyterlab-cpu/shell_helpers.sh
  output/jupyterlab-pytorch/shell_helpers.sh
  output/jupyterlab-tensorflow/shell_helpers.sh
  output/remote-desktop/shell_helpers.sh
  output/rstudio/shell_helpers.sh
  output/sas/shell_helpers.sh
  resources/common/shell_helpers.sh
Labels: auto-deploy

#388 doc(qgis_key): update key details
  README.md
  output/remote-desktop/README.md
  resources/remote-desktop/README.md
Labels: kind/docs
